name: Generate pacman animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: List files in the directory
        run: ls -la

      - name: move to custom output dir
        run: |
          mkdir -p dist/pacman
          mv pacman-contribution-graph.svg dist/pacman/

      - name: push pacman svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist/pacman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
